import type { Dataset } from '../domain/models';
import { functionTypeMeta } from '../domain/functionTypes';
import { expenseCategoryMeta } from '../domain/categories';
import {
  buildCollectionReport, buildExpenseReport, buildFamilyReport, buildFunctionReport,
  buildPaymentMethodReport, buildPersonReport, buildReturnMoiReport,
  buildTopContributors, buildVillageReport, selectOverview, type DateRange,
} from '../domain/selectors';
import { formatDate, formatDateLong, formatMonth } from '../utils/date';
import { formatMoney } from '../utils/format';

/** Escapes text for interpolation into the print HTML. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const STYLES = `
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, "Helvetica Neue", Roboto, sans-serif;
    color: #161430; margin: 0; padding: 28px 24px 40px;
  }
  h1 { font-size: 22px; margin: 0 0 4px; color: #4C1D95; }
  .sub { font-size: 12px; color: #6B7280; margin-bottom: 20px; }
  h2 { font-size: 15px; margin: 26px 0 10px; color: #161430;
       border-bottom: 2px solid #EDE7FB; padding-bottom: 6px; }
  .tiles { display: flex; gap: 10px; margin-bottom: 8px; }
  .tile { flex: 1; background: #F6F3FE; border-radius: 10px; padding: 12px; }
  .tile .k { font-size: 10px; color: #6B7280; text-transform: uppercase;
             letter-spacing: .4px; }
  .tile .v { font-size: 16px; font-weight: 700; color: #4C1D95; margin-top: 3px; }
  table { width: 100%; border-collapse: collapse; font-size: 11.5px; }
  th { text-align: left; background: #F4F5FA; color: #5A5B77; font-weight: 600;
       padding: 8px 10px; border-bottom: 1px solid #E3E5EE; }
  td { padding: 8px 10px; border-bottom: 1px solid #F0F1F6; }
  td.num, th.num { text-align: right; white-space: nowrap; }
  tr:nth-child(even) td { background: #FBFBFE; }
  tfoot td { font-weight: 700; background: #F6F3FE; border-top: 2px solid #EDE7FB; }
  .foot { margin-top: 28px; font-size: 10px; color: #9CA3AF; text-align: center; }
`;

function page(title: string, subtitle: string, body: string, householdName: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>${STYLES}</style></head><body>
    <h1>${esc(title)}</h1>
    <div class="sub">${esc(subtitle)}</div>
    ${body}
    <div class="foot">Generated by Moi Manager for ${esc(householdName)} on ${esc(
      formatDateLong(new Date().toISOString().slice(0, 10)),
    )}</div>
    </body></html>`;
}

function tiles(items: Array<{ k: string; v: string }>): string {
  return `<div class="tiles">${items
    .map((i) => `<div class="tile"><div class="k">${esc(i.k)}</div><div class="v">${esc(i.v)}</div></div>`)
    .join('')}</div>`;
}

function table(headers: string[], rows: string[][], numericFrom = 1, footer?: string[]): string {
  const head = headers
    .map((h, i) => `<th class="${i >= numericFrom ? 'num' : ''}">${esc(h)}</th>`)
    .join('');
  const body = rows
    .map(
      (row) =>
        `<tr>${row
          .map((cell, i) => `<td class="${i >= numericFrom ? 'num' : ''}">${esc(cell)}</td>`)
          .join('')}</tr>`,
    )
    .join('');
  const foot = footer
    ? `<tfoot><tr>${footer
        .map((cell, i) => `<td class="${i >= numericFrom ? 'num' : ''}">${esc(cell)}</td>`)
        .join('')}</tr></tfoot>`
    : '';
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody>${foot}</table>`;
}

function rangeLabel(range?: DateRange): string {
  if (!range?.from && !range?.to) return 'All time';
  return `${range?.from ? formatDate(range.from) : 'Start'} – ${
    range?.to ? formatDate(range.to) : 'Today'
  }`;
}

export type ReportKind =
  | 'summary' | 'function' | 'person' | 'village' | 'family' | 'return-moi'
  | 'top-contributors' | 'expense' | 'payment-method' | 'collection';

/** Renders any report as printable HTML, used for both PDF export and preview. */
export function buildReportHtml(
  kind: ReportKind,
  data: Dataset,
  range?: DateRange,
): { html: string; title: string } {
  const who = data.profile.name || 'My household';
  const period = rangeLabel(range);

  switch (kind) {
    case 'function': {
      const report = buildFunctionReport(data, range);
      const body =
        tiles([
          { k: 'Total collection', v: formatMoney(report.totalCollection) },
          { k: 'Functions', v: String(report.totalFunctions) },
          { k: 'Guests', v: String(report.totalGuests) },
          { k: 'Average moi', v: formatMoney(report.averageMoi) },
        ]) +
        '<h2>Functions</h2>' +
        table(
          ['Function', 'Date', 'Entries', 'Guests', 'Collected', 'Expenses'],
          report.rows.map((r) => [
            `${functionTypeMeta(r.type).emoji}  ${r.title}`,
            formatDate(r.date),
            String(r.entryCount),
            String(r.guestCount),
            formatMoney(r.collected),
            r.expenses ? formatMoney(r.expenses) : '—',
          ]),
          2,
          [
            'Total',
            '',
            String(report.rows.reduce((s, r) => s + r.entryCount, 0)),
            String(report.totalGuests),
            formatMoney(report.totalCollection),
            formatMoney(report.totalExpenses),
          ],
        );
      return { html: page('Function Report', period, body, who), title: 'Function Report' };
    }

    case 'person': {
      const rows = buildPersonReport(data, range);
      const total = rows.reduce((s, r) => s + r.total, 0);
      const body =
        tiles([
          { k: 'People', v: String(rows.length) },
          { k: 'Total received', v: formatMoney(total) },
        ]) +
        '<h2>People</h2>' +
        table(
          ['Name', 'Village', 'Functions', 'Total given'],
          rows.map((r) => [r.name, r.village ?? '—', String(r.functionCount), formatMoney(r.total)]),
          2,
          ['Total', '', '', formatMoney(total)],
        );
      return { html: page('Person Report', period, body, who), title: 'Person Report' };
    }

    case 'village':
    case 'family': {
      const rows = kind === 'village' ? buildVillageReport(data, range) : buildFamilyReport(data, range);
      const label = kind === 'village' ? 'Village' : 'Family';
      const total = rows.reduce((s, r) => s + r.total, 0);
      const body =
        tiles([
          { k: `${label}s`, v: String(rows.length) },
          { k: 'Total received', v: formatMoney(total) },
        ]) +
        `<h2>${label} wise collection</h2>` +
        table(
          [label, 'People', 'Entries', 'Total'],
          rows.map((r) => [r.label, String(r.peopleCount), String(r.entryCount), formatMoney(r.total)]),
          1,
          ['Total', '', '', formatMoney(total)],
        );
      return { html: page(`${label} Report`, period, body, who), title: `${label} Report` };
    }

    case 'return-moi': {
      const rows = buildReturnMoiReport(data, { withinDays: 365 });
      const body =
        tiles([
          { k: 'Upcoming functions', v: String(rows.length) },
          { k: 'Suggested total', v: formatMoney(rows.reduce((s, r) => s + r.suggested, 0)) },
        ]) +
        '<h2>Moi you may need to return</h2>' +
        table(
          ['Person', 'Function', 'Date', 'In days', 'Last received', 'Suggested'],
          rows.map((r) => [
            r.person.name,
            r.event.title,
            formatDate(r.event.date),
            String(r.daysAway),
            formatMoney(r.lastReceived),
            formatMoney(r.suggested),
          ]),
          3,
        );
      return { html: page('Return Moi Report', 'Upcoming guest functions', body, who), title: 'Return Moi Report' };
    }

    case 'top-contributors': {
      const rows = buildTopContributors(data, 50, range);
      const body =
        '<h2>Top contributors</h2>' +
        table(
          ['#', 'Name', 'Village', 'Functions', 'Total', 'Share'],
          rows.map((r) => [
            String(r.rank),
            r.name,
            r.village ?? '—',
            String(r.functionCount),
            formatMoney(r.total),
            `${(r.share * 100).toFixed(1)}%`,
          ]),
          3,
        );
      return { html: page('Top Contributors', period, body, who), title: 'Top Contributors' };
    }

    case 'expense': {
      const report = buildExpenseReport(data, range);
      const body =
        tiles([
          { k: 'Total spent', v: formatMoney(report.total) },
          { k: 'Categories', v: String(report.rows.length) },
          { k: 'Cash', v: formatMoney(report.split.cash) },
          { k: 'UPI', v: formatMoney(report.split.upi) },
        ]) +
        '<h2>By category</h2>' +
        table(
          ['Category', 'Items', 'Total', 'Share'],
          report.rows.map((r) => [
            `${r.emoji}  ${r.label}`,
            String(r.count),
            formatMoney(r.total),
            report.total ? `${((r.total / report.total) * 100).toFixed(1)}%` : '0%',
          ]),
          1,
          ['Total', '', formatMoney(report.total), '100%'],
        );
      return { html: page('Expense Report', period, body, who), title: 'Expense Report' };
    }

    case 'payment-method': {
      const report = buildPaymentMethodReport(data, range);
      const body =
        '<h2>Moi received</h2>' +
        table(
          ['Method', 'Entries', 'Amount'],
          [
            ['Cash', String(report.moiCounts.cash), formatMoney(report.moi.cash)],
            ['UPI', String(report.moiCounts.upi), formatMoney(report.moi.upi)],
            ['Other', String(report.moiCounts.other), formatMoney(report.moi.other)],
          ],
          1,
          ['Total', '', formatMoney(report.moi.total)],
        ) +
        '<h2>Expenses paid</h2>' +
        table(
          ['Method', 'Amount'],
          [
            ['Cash', formatMoney(report.expenses.cash)],
            ['UPI', formatMoney(report.expenses.upi)],
            ['Other', formatMoney(report.expenses.other)],
          ],
          1,
          ['Total', formatMoney(report.expenses.total)],
        );
      return {
        html: page('Payment Method Report', period, body, who),
        title: 'Payment Method Report',
      };
    }

    case 'collection': {
      const report = buildCollectionReport(data, range);
      const body =
        tiles([
          { k: 'Total collected', v: formatMoney(report.total) },
          { k: 'Months', v: String(report.rows.length) },
          { k: 'Average entry', v: formatMoney(report.averageEntry) },
        ]) +
        '<h2>Month by month</h2>' +
        table(
          ['Month', 'Entries', 'Collected'],
          report.rows.map((r) => [
            formatMonth(`${r.month}-01`), String(r.entryCount), formatMoney(r.total),
          ]),
          1,
          ['Total', '', formatMoney(report.total)],
        );
      return {
        html: page('Moi Collection Report', period, body, who),
        title: 'Moi Collection Report',
      };
    }

    case 'summary':
    default: {
      const overview = selectOverview(data);
      const functions = buildFunctionReport(data, range);
      const villages = buildVillageReport(data, range);
      const top = buildTopContributors(data, 10, range);
      const body =
        tiles([
          { k: 'Functions', v: String(overview.functionCount) },
          { k: 'Total moi', v: formatMoney(overview.totalMoi) },
          { k: 'People', v: String(overview.peopleCount) },
          { k: 'Entries', v: String(overview.entryCount) },
          { k: 'Spent', v: formatMoney(overview.totalExpenses) },
        ]) +
        '<h2>Functions</h2>' +
        table(
          ['Function', 'Date', 'Entries', 'Collected'],
          functions.rows.map((r) => [
            r.title, formatDate(r.date), String(r.entryCount), formatMoney(r.collected),
          ]),
          2,
          ['Total', '', '', formatMoney(functions.totalCollection)],
        ) +
        '<h2>By village</h2>' +
        table(
          ['Village', 'People', 'Total'],
          villages.map((r) => [r.label, String(r.peopleCount), formatMoney(r.total)]),
          1,
        ) +
        '<h2>Top contributors</h2>' +
        table(
          ['#', 'Name', 'Total'],
          top.map((r) => [String(r.rank), r.name, formatMoney(r.total)]),
          2,
        ) +
        '<h2>Expenses by category</h2>' +
        table(
          ['Category', 'Items', 'Total'],
          buildExpenseReport(data, range).rows.map((r) => [
            `${expenseCategoryMeta(r.key).emoji}  ${r.label}`, String(r.count), formatMoney(r.total),
          ]),
          1,
        );
      return { html: page('Moi Summary', period, body, who), title: 'Moi Summary' };
    }
  }
}
